import React from 'react';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../styles/Post.module.css'

const SinglePost = ({ data }) => {
  return (
    <>
    <Head>
        <title>{data.title} - Ansh Kaushal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
    <div className={styles.content}>
      <h1 className={styles.title}>{data.title}</h1>
      <img src={data.image} className={styles.descImg} alt="no"/>
      <div dangerouslySetInnerHTML={{ __html: data.content }} className={styles.body}/>
      <p className={styles.desc}>{data.description}</p>
      <button className={styles.button}><Link href='/posts'>Back</Link></button>
    </div>
    </>
  );
};

export default SinglePost;
