import Link from "next/link";
import Head from "next/head";
import styles from "../../styles/Posts.module.css";

const Posts = ({ data }) => {
  return (
    <>
    <Head>
        <title>Blog - Peaceture Photography</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo-black.png" />
      </Head>
    <div className={styles.posts}>
      <h1 className={styles.heading}>All Posts❤️</h1>
        {data?.map((ev) => (
          <div className={styles.postGrid} key={ev.id}>
          <Link key={ev.id} href={`/posts/${ev.id}`} passHref legacyBehavior>
            <a className={styles.card}>
              <h2 className={styles.title}>{ev.title}</h2>
            </a>
          </Link>
              <p>By <a style={{color:"#aaa"}} href="https://instagram.com/anshhkaushal">@AnshKaushal</a></p>
      </div>
        ))}
    </div>
</>
  );
};

export default Posts;

export async function getStaticProps() {
  const { posts } = await import("../../data/data.json");
  return {
    props: {
      data: posts,
    },
  };
}
