import React from "react";
import Head from "next/head";
import Image from "next/image";
import picture from "../public/images/hero-bg-3000.jpg";
import Link from "next/link";

export default function about() {
  return (
    <>
      <Head>
        <title>About Me - Ansh Kaushal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/images/my-img-modified.png"
        />
      </Head>

      <div className="about">
        <h1>About Me</h1>
        <Image src={picture} alt="pic" height={410} />
        <p>
          Hi, I am Ansh Kaushal, A Web designer and a passionate photographer. I
          am 19yrs of age and I have a really good experience in Web designing.
          I used to code when I was a little age, and i developed this quality
          of coding eventually!. By the way, check out my{" "}
          <Link href="/projects">projects</Link>.
          <br />
          <br />I love to make new projects and collab with other people to
          develop new projects. I really 💖 photography and I really enjoy doing
          it. I click photographs in the meantime when I am not coding.
        </p>
        <div className="back">
          <h2>Background :</h2>
          <ol>
            <li>Studied at Sri Aurobindo Public School, Baddi</li>
            <li>Got interested in coding in 11th standard</li>
            <li>Studied Html, Css & javascript during lockdown</li>
            <li>Completed the course during first year</li>
            <li>Interested in python and c++</li>
            <li>Made many commits to github profile in 2022</li>
          </ol>
          <br />
          <br />
          <h2>Some courses I have completed :</h2>
          <ol>
            <li>
              Udemy : Complete Web development bootcamp{" "}
              <Link
                href="https://www.udemy.com/course/the-complete-web-development-bootcamp/"
                target="_blank"
                rel="noreferrer"
              >
                Link
              </Link>
              <br />
              View certificate{" "}
              <Link
                href="/images/udemyCertificate.pdf"
                target="_blank"
                rel="noreferrer"
              >
                here
              </Link>
            </li>
            <li>
              Udemy : Javascript DSA Masterclass{" "}
              <Link
                href="https://www.udemy.com/course/js-algorithms-and-data-structures-masterclass/"
                target="_blank"
                rel="noreferrer"
              >
                Link
              </Link>
              <br />
              View certificate{" "}
              <Link
                href="/images/udemyCertificate.pdf"
                target="_blank"
                rel="noreferrer"
              >
                here
              </Link>
            </li>
            <li>
              Youtube : C beginner course{" "}
              <Link
                href="https://youtu.be/irqbmMNs2Bo"
                target="_blank"
                rel="noreferrer"
              >
                Link
              </Link>
            </li>
            <li>
              Youtube : NextJs Full course{" "}
              <Link
                href="https://youtube.com/playlist?list=PLu0W_9lII9agtWvR_TZdb_r0dNI8-lDwG"
                target="_blank"
                rel="noreferrer"
              >
                Link
              </Link>
            </li>
            <li>
              Edx : Introduction to Cloud Development <br />
              with HTML, CSS, and JavaScript{" "}
              <Link
                href="https://learning.edx.org/course/course-v1:IBM+CAD101EN+2T2020/home"
                target="_blank"
                rel="noreferrer"
              >
                Link
              </Link>
              <br />
              View certificate{" "}
              <Link href="/images/EdxCertificate.pdf" target="_blank" rel="noreferrer">
                here
              </Link>
            </li>
            <li>
              <Image
                src="https://www.codewars.com/users/anshhkaushal/badges/small"
                alt=""
                style={{
                  width: "300px",
                  height: "25px",
                  marginTop: "0.6rem",
                  border: "1px solid #efefef",
                }}
                width={120} height={30}
              />{" "}
              <Link
                href="https://www.codewars.com/users/anshhkaushal"
                target="_blank"
                rel="noreferrer"
              >{" "}
               Codewars
              </Link>{" "}
              ranking.
            </li>
            <li>
              <Link
                href="https://www.codechef.com/users/anshhkaushal"
                target="_blank"
                rel="noreferrer"
              >
                CodeChef
              </Link>{" "}
              1🌟 Coder
            </li>
            <li>
              Beginner{" "}
              <Link href="https://unity.com" target="_blank" rel="noreferrer">
                Unity
              </Link>{" "}
              Development
            </li>
          </ol>
          <h3>Want to know more? Contact me!</h3>
          <Link href="/contact" className="btn">
            Contact me
          </Link>
        </div>
      </div>
    </>
  );
}
