import React from "react";
import Head from "next/head";

export default function about() {
  return (
    <>
      <Head>
        <title>Ansh Kaushal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://anshkaushal.netlify.app/static/media/bg.994bd6f74b2caa65237f.png"
        />
      </Head>

      <div class="about">
        <h1>About Me</h1>
        <img src="/images/hero-bg-3000.jpg" alt="pic" />
        <p>
          Hi, I am Ansh Kaushal, A Web designer and a passionate photographer. I
          am 19yrs of age and I have a really good experience in Web designing.
          I used to code when I was a little age, and i developed this quality
          of coding eventually!. By the way, check out my{" "}
          <a href="/projects">projects</a>.
          <br />
          <br />I love to make new projects and collab with other people to
          develop new projects. I really 💖 photography and I really enjoy doing
          it. I click photographs in the meantime when I am not coding.
        </p>
        <div class="back">
          <h2>Background :</h2>
          <ol>
            <li>Studied at Sri Aurobindo Public School, Baddi</li>
            <li>Got interested in coding in 11th standard</li>
            <li>Studied Html, Css & javascript during lockdown</li>
            <li>Completed the course during first year</li>
            <li>Interested in python and c++</li>
            <li>Made many commits to github profile in 2022</li>
          </ol>
          <br />
          <br />
          <h2>Some courses I have completed :</h2>
          <ol>
            <li>
              Udemy : Complete Web development bootcamp{" "}
              <a
                href="https://www.udemy.com/course/the-complete-web-development-bootcamp/"
                target="_blank"
              >
                Link
              </a>
              <br />
              View certificate{" "}
              <a href="/images/udemyCertificate.pdf" target="_blank">
                here
              </a>
            </li>
            <li>
              Youtube : C beginner course{" "}
              <a href="https://youtu.be/irqbmMNs2Bo" target="_blank">
                Link
              </a>
            </li>
            <li>
              Youtube : NextJs Full course{" "}
              <a href="https://youtube.com/playlist?list=PLu0W_9lII9agtWvR_TZdb_r0dNI8-lDwG">
                Link
              </a>
            </li>
            <li>
              Edx : Introduction to Cloud Development <br />
              with HTML, CSS, and JavaScript{" "}
              <a
                href="https://learning.edx.org/course/course-v1:IBM+CAD101EN+2T2020/home"
                target="_blank"
              >
                Link
              </a>
              <br />
              View certificate{" "}
              <a href="/images/EdxCertificate.pdf" target="_blank">
                here
              </a>
            </li>
            <li>
              <img
                src="https://www.codewars.com/users/anshhkaushal/badges/small"
                alt=""
                style={{width: '300px', marginTop: '0.6rem',border: '1px solid #efefef'}}
              />{" "}
              <a
                href="https://www.codewars.com/users/anshhkaushal"
                target="_blank"
              >
                Codewars
              </a>{" "}
              ranking.
            </li>
            <li>
              <a
                href="https://www.codechef.com/users/anshhkaushal"
                target="_blank"
              >
                CodeChef
              </a>{" "}
              1🌟 Coder
            </li>
            <li>
              Beginner{" "}
              <a href="https://unity.com" target="_blank">
                Unity
              </a>{" "}
              Development
            </li>
          </ol>
          <h3>Want to know more? Contact me!</h3>
          <a href="/contact" class="btn">
            Contact me
          </a>
        </div>
      </div>
    </>
  );
}
