import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Typewriter from "typewriter-effect";
import profilePic from '../public/images/my-img-modified.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Ansh Kaushal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://anshkaushal.netlify.app/static/media/bg.994bd6f74b2caa65237f.png"
        />
      </Head>

      <div className="container">
        <div className="upper">
          <Image src={profilePic} alt="profile pic"/>
          <h1>Hey, It's Ansh Kaushal</h1>
        </div>
        <div className="desc">
          <h2 style={{textAlign:'center'}}>
            I am a <Typewriter
              options={{
                strings: ["Web Developer", "Beginner Programmer", "Student", "Designer"],
                autoStart: true,
                loop: true,
              }}  />
          </h2>
        </div>
        <div className="intro">
          <h3>I like to :</h3>
          <ol>
            <li>Fiddle on <span>Figma</span></li>
            <li>Help in <span>open-source</span> contribution</li>
            <li>Helping fellowmates in <span>coding</span></li>
            <li>
              Practicing on{" "}
              <Link href="https://codechef.com" target="_blank" rel="noreferrer">
                Codechef
              </Link>{" "}
              and{" "}
              <Link href="https://codewars.com" target="_blank" rel="noreferrer">
                Codewars
              </Link>
              .
            </li>
            <br />
            <li>Making websites in <span>Nextjs</span> & <span>ReactJs</span></li>
            <li>Modelling in <span>Blender</span></li>
            <li>Solving <span>real life</span> problems</li>
            <li>Making existing technologies <span>better</span>.</li>
          </ol>
        </div>
        <div className="intro">
          <h3>Languages i have learned :</h3>
          <ol>
            <li>Html</li>
            <li>Css</li>
            <li>Javascript & Typescript</li>
            <li>Node.Js</li>
            <br />
            <li>ReactJs & NextJs</li>
            <li>C/C++ (Beginner)</li>
            <li>Beginner Python</li>
            <li>Blender, Figma & Unity</li>
          </ol>
        </div>
      </div>

      <div className="links">
        <div className="con">
          <h3>Contact Me</h3>
          <p>I am available for freelancing!</p>
          <Link href="/contact" className="btn">
            Contact Me
          </Link>
        </div>
        <div className="abo">
          <h3>Still not satisfied?</h3>
          <p>Let's learn more about me</p>
          <Link href="/about" className="btn">
            About Me
          </Link>
        </div>
      </div>
    </>
  );
}
