import Head from "next/head";
import Typewriter from "typewriter-effect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ansh Kaushal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://anshkaushal.netlify.app/static/media/bg.994bd6f74b2caa65237f.png"
        />
      </Head>

      <div class="container">
        <div class="upper">
          <img src="/images/my-img-modified.png" alt="profile pic" />
          <h1>Hey, It's Ansh Kaushal</h1>
        </div>
        <div class="desc">
          <h2 style={{textAlign:'center'}}>
            I am a <Typewriter
              options={{
                strings: ["Web Developer", "Beginner Programmer", "Student", "Designer"],
                autoStart: true,
                loop: true,
              }}  />
          </h2>
        </div>
        <div class="intro">
          <h3>I like to :</h3>
          <ol>
            <li>Fiddle on Figma</li>
            <li>Help in open-source contribution</li>
            <li>Helping fellowmates in coding</li>
            <li>
              Practicing on{" "}
              <a href="https://codechef.com" target="_blank">
                Codechef
              </a>{" "}
              and{" "}
              <a href="https://codewars.com" target="_blank">
                Codewars
              </a>
              .
            </li>
            <br />
            <li>Making wesbites in Nextjs & ReactJs</li>
            <li>Modelling in blender</li>
            <li>Solving real life problems</li>
            <li>Making existing technologies better.</li>
          </ol>
        </div>
        <div class="intro">
          <h3>Languages i have learned :</h3>
          <ol>
            <li>Html</li>
            <li>Css</li>
            <li>Javascript & Typescript</li>
            <li>Node.Js</li>
            <br />
            <li>ReactJs & NextJs</li>
            <li>C/C++</li>
            <li>Beginner Python</li>
            <li>Blender, Figma & Unity</li>
          </ol>
        </div>
      </div>

      <div class="links">
        <div class="con">
          <h3>Contact Me</h3>
          <p>I am available for freelancing!</p>
          <a href="/contact" class="btn">
            Contact Me
          </a>
        </div>
        <div class="abo">
          <h3>Still not satisfied?</h3>
          <p>Let's learn more about me</p>
          <a href="/about" class="btn">
            About Me
          </a>
        </div>
      </div>
    </>
  );
}
